// Includes for root dictionary creation
#include "CalCluster.h"
#include "CalHit.h"
#include "Event.h"
#include "EventHeader.h"
#include "HodoCluster.h"
#include "HodoHit.h"
#include "TriggerData.h"
#include "VTPData.h"
#include "TSData.h"
#include "Particle.h"
#include "MCParticle.h"
#include "Track.h"
#include "Vertex.h"
#include "TrackerHit.h"
#include "MCTrackerHit.h"
#include "MCEcalHit.h"
#include "RawSvtHit.h"
